import type { Board, Task, User } from "./types";

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Alice Johnson",
    email: "alice@example.com",
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "user-2",
    name: "Bob Smith",
    email: "bob@example.com",
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "user-3",
    name: "Carol Davis",
    email: "carol@example.com",
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "current-user",
    name: "You",
    email: "you@example.com",
    avatar: "/placeholder.svg?height=32&width=32",
  },
];

export const mockBoards: Board[] = [
  {
    id: "board-1",
    name: "Website Redesign",
    description: "Complete redesign of the company website",
    columns: [
      { id: "todo", title: "To Do", color: "#ef4444" },
      { id: "in-progress", title: "In Progress", color: "#f59e0b" },
      { id: "done", title: "Done", color: "#10b981" },
    ],
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "board-2",
    name: "Mobile App Development",
    description: "Development of the new mobile application",
    columns: [
      { id: "todo", title: "To Do", color: "#ef4444" },
      { id: "in-progress", title: "In Progress", color: "#f59e0b" },
      { id: "done", title: "Done", color: "#10b981" },
    ],
    createdAt: "2024-01-10T09:00:00Z",
  },
];

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Design new homepage layout",
    description: "Create wireframes and mockups for the new homepage design",
    status: "in-progress",
    priority: "high",
    assigneeId: "user-1",
    dueDate: "2024-02-15T00:00:00Z",
    tags: ["design", "homepage", "ui"],
    attachments: [],
    comments: [
      {
        id: "comment-1",
        content:
          "Started working on the wireframes. Should have initial draft by tomorrow.",
        authorId: "user-1",
        createdAt: "2024-01-20T14:30:00Z",
      },
    ],
    boardId: "board-1",
    createdAt: "2024-01-18T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "task-2",
    title: "Set up development environment",
    description: "Configure development tools and dependencies",
    status: "done",
    priority: "medium",
    assigneeId: "user-2",
    dueDate: "2024-01-25T00:00:00Z",
    tags: ["setup", "development"],
    attachments: [],
    comments: [],
    boardId: "board-1",
    createdAt: "2024-01-16T09:00:00Z",
    updatedAt: "2024-01-22T16:00:00Z",
  },
  {
    id: "task-3",
    title: "Implement user authentication",
    description:
      "Add login and registration functionality with proper security measures",
    status: "todo",
    priority: "high",
    assigneeId: "user-3",
    dueDate: "2024-02-20T00:00:00Z",
    tags: ["authentication", "security", "backend"],
    attachments: [],
    comments: [],
    boardId: "board-1",
    createdAt: "2024-01-19T11:00:00Z",
    updatedAt: "2024-01-19T11:00:00Z",
  },
  {
    id: "task-4",
    title: "Create responsive navigation",
    description: "Design and implement mobile-friendly navigation menu",
    status: "todo",
    priority: "medium",
    assigneeId: "user-1",
    dueDate: "2024-02-10T00:00:00Z",
    tags: ["navigation", "responsive", "ui"],
    attachments: [],
    comments: [],
    boardId: "board-1",
    createdAt: "2024-01-20T08:00:00Z",
    updatedAt: "2024-01-20T08:00:00Z",
  },
  {
    id: "task-5",
    title: "API integration for user data",
    description: "Connect frontend with backend API for user management",
    status: "in-progress",
    priority: "high",
    assigneeId: "user-2",
    dueDate: "2024-02-18T00:00:00Z",
    tags: ["api", "integration", "backend"],
    attachments: [],
    comments: [
      {
        id: "comment-2",
        content: "API endpoints are ready, starting frontend integration now.",
        authorId: "user-2",
        createdAt: "2024-01-21T10:15:00Z",
      },
    ],
    boardId: "board-1",
    createdAt: "2024-01-17T13:00:00Z",
    updatedAt: "2024-01-21T10:15:00Z",
  },
  // Mobile App Development Board Tasks
  {
    id: "task-6",
    title: "Design app architecture",
    description:
      "Plan the overall structure and data flow of the mobile application",
    status: "done",
    priority: "high",
    assigneeId: "user-3",
    dueDate: "2024-01-30T00:00:00Z",
    tags: ["architecture", "planning", "mobile"],
    attachments: [],
    comments: [],
    boardId: "board-2",
    createdAt: "2024-01-12T09:00:00Z",
    updatedAt: "2024-01-28T17:00:00Z",
  },
  {
    id: "task-7",
    title: "Implement push notifications",
    description: "Add push notification functionality for user engagement",
    status: "in-progress",
    priority: "medium",
    assigneeId: "user-1",
    dueDate: "2024-02-25T00:00:00Z",
    tags: ["notifications", "mobile", "engagement"],
    attachments: [],
    comments: [],
    boardId: "board-2",
    createdAt: "2024-01-15T14:00:00Z",
    updatedAt: "2024-01-22T09:00:00Z",
  },
  {
    id: "task-8",
    title: "Create onboarding flow",
    description: "Design and implement user onboarding experience",
    status: "todo",
    priority: "low",
    assigneeId: null,
    dueDate: "2024-03-01T00:00:00Z",
    tags: ["onboarding", "ux", "mobile"],
    attachments: [],
    comments: [],
    boardId: "board-2",
    createdAt: "2024-01-18T16:00:00Z",
    updatedAt: "2024-01-18T16:00:00Z",
  },
];
